// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopCatalog.Service.Data;

#nullable disable

namespace ShopCatalog.Service.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopCatalog.Service.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "פירות וירקות"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "מוצרי חלב"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "בשר ודגים"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "מאפים"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "יבשים ושימורים"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "ניקיון"
                        });
                });

            modelBuilder.Entity("ShopCatalog.Service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "עגבניות",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "מלפפונים",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "בננות",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "תפוחים",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "גזר",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "חסה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "חלב 3%",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "קוטג' 5%",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "גבינה צהובה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "יוגורט טבעי",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "חמאה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "שמנת מתוקה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "חזה עוף",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "שניצל הודו",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "בשר טחון",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "פילה סלמון",
                            Unit = "ק\"ג"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "נקניקיות",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "לחם אחיד פרוס",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Name = "לחמניות",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "פיתות",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Name = "חלה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Name = "בורקס גבינה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Name = "אורז",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Name = "פסטה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Name = "קמח",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Name = "סוכר",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Name = "טונה בשמן",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Name = "תירס משומר",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Name = "נוזל כלים",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Name = "אבקת כביסה",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Name = "מגבות נייר",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            Name = "שקיות זבל",
                            Unit = "יח'"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            Name = "מטהר אוויר",
                            Unit = "יח'"
                        });
                });

            modelBuilder.Entity("ShopCatalog.Service.Models.Product", b =>
                {
                    b.HasOne("ShopCatalog.Service.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopCatalog.Service.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
